spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/taqreem_ecommerce
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: admin
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
    servlet:
        multipart:
            max-file-size: 200MB
            max-request-size: 200MB
    # OAuth2 Configuration (commented out for now)
    # security:
    #     oauth2:
    #         client:
    #             registration:
    #                 google:
    #                     client-id: ${GOOGLE_CLIENT_ID:323341037163-k0e5fa261jg00ak74qsmrooiegd1qunh.apps.googleusercontent.com}
    #                     client-secret: ${GOOGLE_CLIENT_SECRET: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}
    #                     authorization-grant-type: authorization_code
    #                     scope:
    #                     - profile
    #                     - email
    mail:
        host: smtp.gmail.com
        port: 587
        username: info.alamgirhussain@gmail.com
        password: mnbs orsv gwsj pfsz
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
                    connectiontimeout: 5000
                    timeout: 3000
                    writetimeout: 5000

cloudflare:
  r2:
    bucket-name: taqreem-dev
    endpoint: https://9cda468137d1fd4eb0b930ade6113b21.r2.cloudflarestorage.com
    access-key-id: 97ce6d7917dd642150f05f8c605978bd
    secret-access-key: 27cea66ff479ba56b48acb6acea0b3aef382579fd035a4fcaf15a3125c9ac1dd
    public-url: https://pub-3c1ab4f1b24e4f518d015c01b73a0fe3.r2.dev